#!/bin/bash
if [-f /user/local/bin/java*]
then
 echo "java present"
 ver=$(java -version)sudo 
else
 echo "java not found"
 sudo yum -y install epel-release java-1.8.0-openjdk-devel
fi
sudo yum install git -y
sudo yum -y install wget
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo yum -y install jenkins
sudo service jenkins start
sudo systemctl enable jenkins
sudo chkconfig jenkins on
sudo setenforce 0
